### ISSUE TITLE
how to get token?

### ISSUE THREAD

**Issue by trouty00** [watkins-matt/home-assistant-google-keep-sync#1]
not an issue as such but no sure how to get the token from home assistant, tried to run the method to get token but done think python is installed on my HA build.

appreciate some pointers either here or in an updated readme

thank
Stu

**Comment by watkins-matt** [comment]
Hi Stu,

You have to download the script to your computer (which has Python installed) and run it. Note that this is just a temporary workaround and might not work on your system. There are issues with certain versions of OpenSSL and the library I am using so, while the script works for me, it may not work if you don't have the same environment. 

I added updated documentation in the readme with fee188a that should make it more clear.
