### ISSUE TITLE
A services to force sync?

### ISSUE THREAD

**Issue by hectorzin** [watkins-matt/home-assistant-google-keep-sync#17]
It is not an issue, it is a suggestion. This could allow automations to sync, when it detects that we are in a supermarket, etc. Maybe limited to not do it more than 1 or 2 times within a 15-minute interval

**Comment by watkins-matt** [comment]
There is actually a way to do this already. You can use the `homeassistant.update_entity` service, and call it with the entity for your todo list or lists. This will force it to refresh.

You can also create a zone for your local store or supermarket, and then combine this in an automation. So when you enter the zone you created you can trigger update_entity. Just be careful not to call it too frequently or you may be rate-limited by Google.

See:
https://www.home-assistant.io/integrations/homeassistant/
https://community.home-assistant.io/t/ha-update-entity/457273/4

**Comment by watkins-matt** [comment]
I'm going to leave this open for now, because I am still considering adding a request_sync service that would intelligently resync everything (instead of having to target an entity) and have a cooldown to prevent calling it too often (which would cause errors otherwise).

**Comment by watkins-matt** [comment]
There is a new request_sync service in the latest version https://github.com/watkins-matt/home-assistant-google-keep-sync/releases/tag/0.9.7 which should fix this issue.
