### ISSUE TITLE
"Automatically Sort Lists" Does not show description

### ISSUE THREAD

**Issue by Erudition** [watkins-matt/home-assistant-google-keep-sync#21]
![image](https://github.com/watkins-matt/home-assistant-google-keep-sync/assets/3915447/467f2495-80c4-4068-9070-910bb2fbffa1)
As you can see, there's no description visible for this option.

Although I found it in the code:
https://github.com/watkins-matt/home-assistant-google-keep-sync/blob/7c62566a0de1d252222133b9c9551748f3f8b86f/custom_components/google_keep_sync/strings.json#L38

**Comment by watkins-matt** [comment]
I wanted to display a description as you can see from the strings.json. 

Unfortunately this seems to be an issue with Home Assistant frontend itself, and not with this addon specifically. The bug can be found at https://github.com/home-assistant/frontend/issues/15536

It should display correctly once it is fixed on the Home Assistant side.
