### ISSUE TITLE
Be careful when copy-pasting an app passcode

### ISSUE THREAD

**Issue by Erudition** [watkins-matt/home-assistant-google-keep-sync#22]
I found that copying the text on Google's App Password screen, I see the text highlighted correctly:
![image](https://github.com/watkins-matt/home-assistant-google-keep-sync/assets/3915447/6211d70d-e2ba-4ad7-af9e-2f23f272176e)

But when pasting into an empty text editor, I get:
![image](https://github.com/watkins-matt/home-assistant-google-keep-sync/assets/3915447/e5597758-7d69-44e2-b77e-8eb10b773dc7)
Note the whitespace at the end!

Might be helpful to warn users about this when pasting into the UI (which just shows dots) or the docker tool, as it will probably give incorrect password errors for this non-obvious reason

**Comment by watkins-matt** [comment]
Definitely a valid concern, but this should not be an issue in practice. Did you try pasting in the version with the space at the end? It should still work regardless.

For all of the input fields, any leading or trailing spaces are typically erroneous and are removed by the code before processing the input. Spaces are valid within a password, but usually users do not intend to add an extra space or spaces at the end of their password. 

There might be a random person out there that intended to put a space at the end of their password, but I'd much rather everything just work for the vast majority of users that did not intend to do so.

**Comment by Erudition** [comment]
Actually, I created this issue because the software did not ignore the space at the end. When I figured it out and removed the space, the passcode started working.
