### ISSUE TITLE
suggestion: ignore trashed/archived lists during config

### ISSUE THREAD

**Issue by jlsjonas** [watkins-matt/home-assistant-google-keep-sync#24]
Hi,

It would be great to reduce configuration clutter by skipping archived(/trashed) lists. (probable [code pointer](https://github.com/watkins-matt/home-assistant-google-keep-sync/blob/a33d63d8fb5bbc257b0305b153592c8e5fd5094b/custom_components/google_keep_sync/api.py#L215))
Perhaps with a toggle just in case you're using this integration as a backup towards archived lists

Thanks for considering!

**Comment by watkins-matt** [comment]
Yes, seems like a reasonable change. Definitely shouldn't be showing lists that are in the trash. Not sure if anyone has a use-case for selecting archived lists. 

I'm inclined to change it so it only shows unarchived/untrashed lists for selection by default. I'll see if I can get code in to fix this before the next version.

**Comment by watkins-matt** [comment]
Fixed in the latest release, [0.9.8](https://github.com/watkins-matt/home-assistant-google-keep-sync/releases/tag/0.9.8)
