### ISSUE TITLE
Making the list visible on the dashboard

### ISSUE THREAD

**Issue by skupu** [watkins-matt/home-assistant-google-keep-sync#30]
Hi @watkins-matt
I'm wondering how to make list visible/timely updated on a dashboard.

I was trying with some automations and scripts but no luck - maybe I'm not advanced enough.
But even gpt 4 couldn't help with the solution...

Please help!

Thank you!

**Comment by watkins-matt** [comment]
Hi,

You just add a todo-list card to your dashboard, selecting the entity created by the integration. It should start with "todo. google_keep". Please see here for more information: https://www.home-assistant.io/dashboards/cards/

Any changes you make in Home Assistant will reflect instantly. Changes made in Google Keep will be updated every 15 minutes.
