### ISSUE TITLE
Integration is already configured for this user.

### ISSUE THREAD

**Issue by linsvensson** [watkins-matt/home-assistant-google-keep-sync#34]
Tried adding my usual account and got this error message, I've never added this integration before.

**Comment by watkins-matt** [comment]
Thanks for the report, I'm pretty sure I know what the issue is. Currently testing out a fix for it.

**Comment by watkins-matt** [comment]
If possible, can you tell me if this issue still occurs using the new beta version 0.9.9b? You would need to go into HACS, select Show Beta versions and choose version 0.9.9b to update to.

**Comment by linsvensson** [comment]
It works with the new beta, thanks!
