### ISSUE TITLE
what are the list to sync

### ISSUE THREAD

**Issue by pippo73** [watkins-matt/home-assistant-google-keep-sync#41]
Hello, 
this is not a bug, but just a question.
I've tried to use this addon, and when I sync it with HA, I get a list of lists
![image](https://github.com/user-attachments/assets/4b3ad083-ed71-4ffe-8eda-f682ebd0148e)

but on keep I have only a list. How to understand what are they?

tnx for the support

**Comment by watkins-matt** [comment]
Hi,

The lists shown are the titles of the lists within your accout in Google Keep. Any note with checkboxes is considered a "list".

Whichever lists you choose here are the ones that will be synchronized with Home Assistant.
