### ISSUE TITLE
Delete Master Token

### ISSUE THREAD

**Issue by Th0tti** [watkins-matt/home-assistant-google-keep-sync#42]
How can I delete the master token?

**Comment by watkins-matt** [comment]
You can delete the authentication information removing the integration from Home Assistant. You would do this by going to Settings->Devices & Services, clicking Google Keep Sync, then click the dropdown next to the configure button, then click delete. This will delete the integration and its stored authentication information. 

You can also delete the cached data by deleting the file in the Home Assistant config folder/.storage/google_keep_sync.your.email@gmail.com.json.
