### ISSUE TITLE
Lists to sync don't show up

### ISSUE THREAD

**Issue by 1onar** [watkins-matt/home-assistant-google-keep-sync#43]
I got everything running but there is no list to sync showing up.

<img width="512" alt="Bildschirmfoto 2024-12-14 um 12 42 47" src="https://github.com/user-attachments/assets/c3709176-812f-49f2-a488-6c735e493c0a" />

Core 2024.12.3
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.8

**Comment by watkins-matt** [comment]
Do you see any errors in the Home Assistant logs? If possible try to update to the latest beta to see if it fixes it. 

Also, the lists will only show up if they have checkboxes and are not archived or in the trash, can you verify that the lists meet that criteria?

**Comment by 1onar** [comment]
> Do you see any errors in the Home Assistant logs?

```
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:324
Erstmals aufgetreten: 15:26:34 (1 Vorkommnisse)
Zuletzt protokolliert: 15:26:34

Detected that custom integration 'google_keep_sync' sets option flow config_entry explicitly, which is deprecated at custom_components/google_keep_sync/config_flow.py, line 52: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'google_keep_sync' custom integration
```

>  If possible try to update to the latest beta to see if it fixes it.

I updated to 0.9.9b2 but there is still no list showing up.

> Also, the lists will only show up if they have checkboxes and are not archived or in the trash, can you verify that the lists meet that criteria?

Is there any way to verify it? I have this list:

<img width="1077" alt="Bildschirmfoto 2024-12-19 um 15 31 47" src="https://github.com/user-attachments/assets/4094631e-2c50-48f8-9299-7d0f85025878" />

I also added a new fresh list:

<img width="1078" alt="Bildschirmfoto 2024-12-19 um 15 33 32" src="https://github.com/user-attachments/assets/4da5516c-7a2f-4166-8d07-0e6528d3ca8e" />

But still it's is empty:

<img width="951" alt="Bildschirmfoto 2024-12-19 um 15 34 28" src="https://github.com/user-attachments/assets/74c47d4e-748b-4d3c-816d-93a84cda73dc" />

My Setup:

<img width="528" alt="Bildschirmfoto 2024-12-19 um 15 35 04" src="https://github.com/user-attachments/assets/2223866f-8706-4fe0-b252-2126f47deeaa" />

Thank you for your effort!

**Comment by watkins-matt** [comment]
Sorry, I think I need to make the documentation a bit more clear. The initial lists you choose have to be on the Google Keep side. 

So you would log into your Google account, then go to keep.google.com and make the lists within Google Keep. Then if you come back to the integration, it should let you choose from the lists in Google Keep.

**Comment by 1onar** [comment]
Sorry for wasting your time. Thank you for your help and code!
