### ISSUE TITLE
Change view, reduce line spacing, adjust font

### ISSUE THREAD

**Issue by noseman2k1** [watkins-matt/home-assistant-google-keep-sync#44]
hello is there a way to reduce the line spacing in the list and if necessary change the font and font color ?

thank you in advance for your feedback

Marc

**Comment by watkins-matt** [comment]
Hi, the integration itself does not control any of the list styling. It just generates todo entities for Home Assistant to display. 

You may be able to change the list styling using something like https://github.com/thomasloven/lovelace-card-mod.
