### ISSUE TITLE
How to use with voice

### ISSUE THREAD

**Issue by pergolafabio** [watkins-matt/home-assistant-google-keep-sync#7]
Hi,

thnx for sharing this component, i'm using also google home, and i see you have a sevice called: todo.add_item

Is it possible to use this service with Google Assisant voice? Is it possible to pass the ingredient as a variable?

thnx

**Comment by watkins-matt** [comment]
This integration does not directly connect with Google Assistant, that is beyond the scope of the integration.

Google Assistant fully integrates with Google Keep, so you can add items to your Keep list with Google Assistant, and then these changes will be synced to Home Assistant after the next sync interval.

For example, you could say "Hey Google, add Milk to the Shopping List" where 'Shopping List' is a named Keep list. Then, choose that list to sync when setting up the integration. The changes will be reflected after synchronization happens.
