### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by BernieV1977** [watkins-matt/home-assistant-google-keep-sync#8]
I tried authentication by GUI and script but no luck. My OpenSSL version is newer:

Current Version Information:
Python  : 3.11.6
OpenSSL : 3.0.11
gkeepapi: 0.14.2
urllib3 : 1.26.18
gpsoauth: 1.0.2
requests: 2.31.0

ERROR:root:Failed to login to Google Keep: ('BadAuthentication', None)

Authentication failed. Please try again with the known working versions:
Python  : 3.11.4
OpenSSL : 1.1.1n
gkeepapi: 0.14.2
urllib3 : 1.26.18
gpsoauth: 1.0.2
requests: 2.31.0

**Comment by superharaldsson** [comment]
Same for me!

**Comment by Stofakiller2** [comment]
Same for me:
Current Version Information:
Python  : 3.11.2
OpenSSL : 3.0.11
gkeepapi: 0.14.2
urllib3 : 1.26.18
gpsoauth: 1.0.2
requests: 2.28.1

I got a bit further to run the pip install as sudo, but still no token and got the same error

**Comment by watkins-matt** [comment]
OpenSSL 3 will not work. This is a known issue with gpsoauth, not with this integration. 

Please use the "Generating a Token Using a Docker Container" instructions from the Readme, other people have had better luck with that.

**Comment by Stofakiller2** [comment]
Sad to see that you have closed it... I think you need to specific write either here and/or in your requirement.txt what version of openssl to use, writing that ver 3 doesnt work dont help us very much
Sure i can pull a docker in my VM, but all have this option...

**Comment by BernieV1977** [comment]
I Don't have a Docker So I Can't use this one 🤥

**Comment by Stofakiller2** [comment]
I just triede the docker version, still no token, i triede with 2 Gmail account, 1 with 2fa and 1 without, Them OpenSSL In the docker is 1.1.1w, i triede to downgrade to 1.1.1n, still no luck…Venlig hilsen/Best Regards,Jan LarsenDen 20. jan. 2024 kl. 11.27 skrev BernieV1977 ***@***.***>:﻿
I Don't have a Docker So I Can't use this one 🤥

**Comment by Stofakiller2** [comment]
> I Don't have a Docker So I Can't use this one 🤥

@BernieV1977 I can send it too you, but off course that means that i need your info, but you can always change the password afterwards... And only would trust me with these sensitive information... Github has no way to send messages to other users, but here in my link to my [Facebook messenger](https://m.me/stofakiller)

**Comment by watkins-matt** [comment]
This issue is not something I can fix directly, it is an issue within another library, gpsoauth.

Right now there are the following options:
- Install docker and use the docker container to get a token.
- Wait until the issue is fixed within gpsoauth, or another means to get a token is implemented.

Please do not solicit passwords from other people here.
